<?php

namespace AppBundle\Repository;

/**
 * GymLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GymLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
