<?php

namespace AppBundle\Repository;

/**
 * GymListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GymListRepository extends \Doctrine\ORM\EntityRepository
{
}
